version: '3.4'

services:
  neos:
    build:
      args: 
        context: development
    environment: 
      FLOW_CONTEXT: Development
    ports:
      - 80:80
    volumes: 
      - ./composer.json:/neos/composer.json
      - ./composer.lock:/neos/composer.lock
      - ./Configuration/:/neos/Configuration/
      - ./DistributionPackages/:/neos/DistributionPackages/