version: '3.4'

services:
  neos:
    image: neosduttweilerde
    build:
      context: .
      args: 
        context: production
    environment: 
      FLOW_CONTEXT: Production
    volumes: 
      - data:/neos/Data/Persistent/
    depends_on: 
      - db
      - cache

  db:
    image: mariadb
    environment: 
      MYSQL_ROOT_PASSWORD: 'db'
      MYSQL_DATABASE: 'neos'
    volumes: 
      - db:/var/lib/mysql

  cache:
    image: redis:alpine
    volumes:
      - cache:/data

volumes:
  db:
  data:
  cache: