version: '3.4'

services:
  neos:
    image: neosduttweilerde:prod
    build:
      context: .
      args: 
        context: production
    environment: 
      FLOW_CONTEXT: Production
      # change this to the real traefik ip once we're in production with it
      FLOW_HTTP_TRUSTED_PROXIES: '*'
    volumes: 
      - data:/neos/Data/Persistent/
    depends_on: 
      - db
      - cache
    restart: unless-stopped
    labels: 
      - traefik.enable=true
      - traefik.docker.network=neosduttweilerde_public
      - traefik.http.routers.neos.rule=Host(`duttweiler.de`, `www.duttweiler.de`)
      - traefik.http.services.neos.loadbalancer.server.port=80
    networks: 
      - internal
      - public

  db:
    image: mariadb
    environment: 
      MYSQL_ROOT_PASSWORD: 'db'
      MYSQL_DATABASE: 'neos'
    volumes: 
      - db:/var/lib/mysql
    restart: unless-stopped
    networks:
      - internal

  cache:
    image: redis:alpine
    volumes:
      - cache:/data
    restart: unless-stopped
    networks:
      - internal

networks: 
  internal:
  public:

volumes:
  db:
  data:
  cache: