-
  name: 'JSON API'
  uriPattern: 'api/(v1/){endpoint}.json'
  defaults:
    '@package': Neos.Neos
    '@controller': Frontend\Node
    '@action': show
    '@format': json
    'node': '/sites/duttweilerde'
  appendExceedingArguments: true

-
  name: 'RSS API'
  uriPattern: 'api/(v1/)news.rss'
  defaults:
    '@package': Neos.Neos
    '@controller': Frontend\Node
    '@action': show
    '@format': atom
    'node': '/sites/duttweilerde'
  appendExceedingArguments: true

-
  name: 'News API :: Atom'
  uriPattern: 'api/(v1/)news.xml'
  defaults:
    '@package': Neos.Neos
    '@controller': Frontend\Node
    '@action': show
    '@format': atom
    'node': '/sites/duttweilerde'
