Neos:
  Flow:
    persistence:
      backendOptions:
        host: db
        driver: pdo_mysql
        dbname: neos
        user: root
        password: db
    mvc:
      routes:
        Neos.Flow: true
    log:
      systemLogger:
        backendOptions:
          logIpAddress: true
    i18n:
      defaultLocale: de
  Neos:
    userInterface:
      defaultLanguage: 'de'
  Imagine:
    driver: Imagick
    enabledDrivers:
      Vips: true
      Imagick: true
      Gd: false
  Media:
    image:
      defaultOptions:
        interlace: null
