Neos:
  Flow:
    persistence:
      backendOptions:
        host: db
        driver: pdo_mysql
        dbname: neos
        user: root
        password: db
    mvc:
      routes:
        Neos.Flow: true
    log:
      systemLogger:
        backendOptions:
          logIpAddress: true
    i18n:
      defaultLocale: de
  Neos:
    userInterface:
      defaultLanguage: 'de'
  Imagine:
    driver: Imagick
    enabledDrivers:
      Vips: true
      Imagick: true
      Gd: false
  Media:
    image:
      defaultOptions:
        interlace: null
Jonnitto:
  PrettyEmbedHelper:
    enableGdprMessage: true
  PrettyEmbedYoutube:
    url:
      playlist:
        embed: 'http://www.youtube-nocookie.com/embed/videoseries?list=%id%'
        href: 'http://www.youtube-nocoockie.com/playlist?list=%id%'
      video:
        embed: 'http://www.youtube-nocookie.com/embed/%id%'
        href: 'http://www.youtube-nocoockie.com/watch?v=%id%'