# Content NodeTypes Groups

TYPO3:
  Neos:
    nodeTypes:
      groups:
        duttweiler-general:
          label: 'Duttweiler - Allgemein'
          position: start
        frontpage:
          label: 'Duttweiler - Startseite'
          position: start
        chronik:
          label: 'Duttweiler - Chronik'
          position: start
        api:
          label: 'Duttweiler - API'
          position: end

    userInterface:
      navigateComponent:
        nodeTree:
          loadingDepth: 2

  Flow:
    i18n:
      defaultLocale: de

    error:
      exceptionHandler:
        renderingGroups:
          'notFoundExceptions':
            matchingStatusCodes: [ 404 ]
            options:
              templatePathAndFilename: 'resource://GSL.DuttweilerDe/Private/Templates/Page/Error.html'
              layoutRootPath: 'resource://TYPO3.Neos/Private/Layouts/'
              format: 'html'
